title: Panama Blue Natural Heritage
copyright: '&copy;2021-2022 Diego J. Lizcano'
baseURL: https://acousticpanama.netlify.app/
languageCode: en-us
theme: hugo-split-gallery-main
DefaultContentLanguage: en
taxonomies:
  location: locations
  season: seasons
params:
  description: Panama Blue Natural Heritage. Acoustic Component. Field report I
  favicon: ''
  footnote: Diego J. Lizcano for Audubon Americas
  galleryLoop: yes
  images: 7D2_1419.jpg
  includeOriginalImage: yes
  map2gpx: en
  paginate: 10
  robots: index, follow
  showTranslations: no
  taxonomies:
    locations:
      icon: location-arrow
    seasons:
      icon: calendar
languages:
  en:
    menu:
      main:
        - identifier: about
          name: About this report
          pre: <i class='fa fa-map-marker'></i>
          url: /about/
          weight: -110
        - name: Field Report
          pre: <i class='fa fa-road'></i>
          url: /field-report/
          weight: -100
    weight: 1
